// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourOfHeroes.Data.EfCore;

namespace TourOfHeroes.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200427141205_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TourOfHeroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr Nice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Narco"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bombasto"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Celeritas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Magneta"
                        },
                        new
                        {
                            Id = 6,
                            Name = "RubberMan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dynama"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dr IQ"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Magma"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tornado"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Wicker Man"
                        });
                });

            modelBuilder.Entity("TourOfHeroes.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Powers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeroId = 1,
                            Name = "Super Strength"
                        },
                        new
                        {
                            Id = 2,
                            HeroId = 1,
                            Name = "Flight"
                        },
                        new
                        {
                            Id = 3,
                            HeroId = 7,
                            Name = "Invisibility"
                        },
                        new
                        {
                            Id = 4,
                            HeroId = 2,
                            Name = "Laser Eyes"
                        },
                        new
                        {
                            Id = 5,
                            HeroId = 2,
                            Name = "Healing Factor"
                        },
                        new
                        {
                            Id = 6,
                            HeroId = 3,
                            Name = "Super Intelligence"
                        },
                        new
                        {
                            Id = 7,
                            HeroId = 4,
                            Name = "Telekinesis"
                        },
                        new
                        {
                            Id = 8,
                            HeroId = 5,
                            Name = "Telepathy"
                        },
                        new
                        {
                            Id = 9,
                            HeroId = 6,
                            Name = "Super Speed"
                        },
                        new
                        {
                            Id = 10,
                            HeroId = 11,
                            Name = "BEEEEEEEEEEEEEEEEEES"
                        });
                });

            modelBuilder.Entity("TourOfHeroes.Power", b =>
                {
                    b.HasOne("TourOfHeroes.Hero", null)
                        .WithMany("Powers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
